"""Render results/experiments/validation/fsa/README.md from the validation JSON artifacts.

Every number in the rendered page is read from a JSON file in the same directory; nothing
is recomputed or typed in by hand.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import _problems as P                                               # noqa: E402

V = P.RESULTS / "experiments/validation/fsa"


def j(name):
    return json.loads((V / name).read_text())


def e(x):
    return "—" if x is None else f"{x:.2e}"


def main():
    s = j("summary.json")
    L = ["# FSA validation (before scientific training)", "",
         "Generated by `chemkan/scripts/fsa/summarize_validation.py` from the JSON files in this "
         "directory. Acceptance criteria: `acceptance_criteria.json` (recorded before any section "
         "ran); amendment: `acceptance_criteria_amendment1.json`.", "",
         "| section | status | file |", "|---|---|---|"]
    for k in "ABCDEFG":
        if k in s:
            st = s[k]["status"] + (f" (original {s[k]['original_status']}, amended)"
                                   if "original_status" in s[k] else "")
            L.append(f"| {k} | {st} | `{s[k].get('amendment_file', s[k]['file'])}` |")
    L += ["", f"**Core validation: {s['core_validation']}**; optional G: {s['optional_G']}.", ""]

    a = j("A_analytic.json")
    L += ["## A. Analytic problem dy/dt = θy", "", "| θ | level | state rel. err | S rel. err | "
          "dL/dθ rel. err | FSA vs autograd |", "|---|---|---|---|---|---|"]
    for c in a["cases"]:
        for lv, v in c["levels"].items():
            L.append(f"| {c['theta']} | {lv} | {e(v['state_rel_err'])} | {e(v['sensitivity_rel_err'])} | "
                     f"{e(v['loss_gradient_rel_err'])} | {e(v['fsa_vs_direct_autograd_rel'])} |")

    b = j("B_functional_equivalence.json")
    L += ["", "## B. Functional form vs existing dynamics wrapper", "",
          "| problem | dtype | max rel. diff |", "|---|---|---|"]
    L += [f"| {r['problem']} | {r['dtype']} | {e(r['metric'])} |" for r in b["rows"]]

    c = j("C_gradients.json")
    L += ["", "## C. FSA vs direct-autograd gradients (float64)", "",
          "Relative L2 difference of the full gradient at L0 (1e-6/1e-8, production), "
          "L1 (1e-8/1e-10), L2 (1e-10/1e-12); per-group values at L2.", "",
          "| problem | L0 | L1 | L2 | groups at L2 | FSA L1→L2 | autograd L1→L2 | FSA L0 vs L2 | pass |",
          "|---|---|---|---|---|---|---|---|---|"]
    for k in c["cases"]:
        lv = k["levels"]
        g = ", ".join(f"{n}: {e(v['relative_l2'])}" for n, v in
                      lv["L2"]["fsa_vs_direct_autograd"].get("groups", {}).items())
        L.append(f"| {k['problem']} | {e(lv['L0']['fsa_vs_direct_autograd']['relative_l2'])} | "
                 f"{e(lv['L1']['fsa_vs_direct_autograd']['relative_l2'])} | "
                 f"{e(lv['L2']['fsa_vs_direct_autograd']['relative_l2'])} | {g} | "
                 f"{e(k['refinement']['fsa_L1_vs_L2'])} | {e(k['refinement']['direct_autograd_L1_vs_L2'])} | "
                 f"{e(k['section10_production']['fsa_L0_vs_fsa_L2']['relative_l2'])} | {k['pass']} |")
    ca = j("C_gradients_amendment1.json")
    L += ["", "Amendment 1 (L3 = 1e-12/1e-14) for the case that missed refinement stability:", ""]
    for k in ca["cases"]:
        if not k["original_pass"]:
            L.append(f"- `{k['problem']}`: FSA vs autograd at L3 {e(k['fsa_vs_direct_autograd_L3']['relative_l2'])}; "
                     f"L2→L3 change FSA {e(k['fsa_L2_vs_L3'])}, autograd {e(k['direct_autograd_L2_vs_L3'])}; "
                     f"production FSA vs L3 {e(k['section10_fsa_L0_vs_fsa_L3']['relative_l2'])} → "
                     f"{'PASS' if k['pass'] else 'FAIL'}")
    L += ["", f"Evidence: `investigation_stage1_refinement.json`. Rationale: {ca['amendment']['rationale']}"]

    d = j("D_state_consistency.json")
    L += ["", "## D. Physical state: augmented FSA solve vs state-only solve", "",
          "Max normalized error vs a 1e-12/1e-14 state-only reference (augmented / state-only).", "",
          "| problem | L0 | L1 | L2 | S L1 vs L2 |", "|---|---|---|---|---|"]
    for k in d["cases"]:
        lv = k["levels"]
        L.append(f"| {k['problem']} | " + " | ".join(
            f"{e(lv[x]['err_augmented'])} / {e(lv[x]['err_state_only'])}" for x in ("L0", "L1", "L2"))
            + f" | {e(k['sensitivity_L1_vs_L2'])} |")

    ev = j("E_independence.json")
    ea = j("E_independence_amendment1.json")
    L += ["", "## E. Trajectory independence", ""]
    for k in ev["cases"]:
        L.append(f"- `{k['problem']}` (batch {k['batch']}): max |dF_b/dx_c|, b≠c = "
                 f"{k['max_abs_cross_derivative']}; batch vs individual at L2: "
                 + ", ".join(f"#{r['train_index']} state {e(r['state_normalized_max'])} / S {e(r['sensitivity_relative'])}"
                             for r in k["batch_vs_individual"])
                 + (f"; other trajectories bit-identical under a T_obs perturbation: "
                    f"{k['stage1_other_trajectories_bit_identical']}" if "stage1_other_trajectories_bit_identical" in k else ""))
    for k in ea["cases"]:
        if not k["original_pass"]:
            L.append(f"- amendment 1, `{k['problem']}` at L3: " + ", ".join(
                f"#{r['train_index']} state {e(r['state_normalized_max'])} / S {e(r['sensitivity_relative'])}"
                for r in k["batch_vs_individual_L3"]) + f" → {'PASS' if k['pass'] else 'FAIL'}")

    f = j("F_production_dtype.json")
    L += ["", "## F. Production dtype (float32, 1e-6/1e-8) vs float64 L2 FSA reference", "",
          "| problem | FSA float32 rel. err | autograd float32 rel. err | NFE FSA / autograd | s FSA / autograd |",
          "|---|---|---|---|---|"]
    for k in f["cases"]:
        L.append(f"| {k['problem']} | {e(k['float32_fsa_vs_float64_reference']['relative_l2'])} | "
                 f"{e(k['float32_direct_autograd_vs_float64_reference']['relative_l2'])} | "
                 f"{k['nfe_float32_fsa']} / {k['nfe_float32_direct_autograd']} | "
                 f"{k['seconds_float32_fsa']:.1f} / {k['seconds_float32_direct_autograd']:.1f} |")

    g = j("G_finite_differences.json")
    L += ["", "## G. Optional finite differences", ""]
    L += [f"- `{k['problem']}` `{k['parameter']}[{k['index']}]`: {k['status']}"
          + (f" (rel. err {e(k['relative_error'])})" if k["relative_error"] is not None else
             " — no two consecutive step sizes agree to 1e-4 (gradient magnitude "
             f"{e(abs(k['fsa_L2']))}; cancellation error dominates)") for k in g["cases"]]

    r = j("resume_validation.json")
    dr = j("da_regression.json")
    sm = j("smoke_summary.json")
    L += ["", "## Resume, direct-autograd regression, smoke tests", "",
          f"- Resume (10 updates vs 5 + resume + 5): **{r['status']}** — "
          + "; ".join(f"{c['case']}: tensors {c['model_tensors_equal']}, Adam {c['optimizer_state_after_10_equal']}, "
                      f"RNG {c['rng_state_equal']}, history {c['history_rows_equal']}" for c in r["cases"]),
          f"- Direct-autograd regression: **{dr['status']}** — "
          + "; ".join(f"{x['name']}: {x['rows_compared']} rows, bit-identical {x['bit_identical']}"
                      for x in dr["results"]),
          f"- Smoke tests: **{sm['status']}** — " + ", ".join(f"{x['name']} {'PASS' if x['pass'] else 'FAIL'}"
                                                             for x in sm["runs"]), ""]
    (V / "README.md").write_text("\n".join(L) + "\n")
    print(f"-> {(V / 'README.md').relative_to(P.ROOT)}")


if __name__ == "__main__":
    main()
